services:
  frontend:
    build: ./Frontend
    ports:
      - "4000:5173"
    depends_on:
      - api-gateway
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - frontend

include:
  - Backend/docker-compose.yml
