services:
  frontend:
    build: ./Frontend
    ports:
      - "4000:5173"
    depends_on:
      - api-gateway
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "api-gateway/health"]
      interval: 5s
      timeout: 5s
      retries: 20

include:
  - Backend/docker-compose.yml
